<?php
/**
 * Drupal Plugin - Module
 *
 * PHP version 5.6
 *
 * @category Plugins
 *
 * @author   Mikhail Protasebich <m.protasevich@smartcat.ai>
 */

use Drupal\tmgmt_smartcat\Database\Migrations;

/**
 * Implements hook_cron()
 *
 * @throws \Drupal\tmgmt\TMGMTException
 */
function tmgmt_smartcat_cron()
{
    // FIXME: Replace with hook_update_N()
    Migrations::run();

    /** @var \Drupal\tmgmt_smartcat\Services\TranslationsExporter $translationsExporter */
    $translationsExporter = \Drupal::service('tmgmt_smartcat.translations_exporter');

    $translationsExporter->continuousExport();

    // TODO: Add cron task for checking Smartcat project status
}
